export enum Permission {
  // User Management
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Device Management
  CREATE_DEVICE = 'CREATE_DEVICE',
  READ_DEVICE = 'READ_DEVICE',
  UPDATE_DEVICE = 'UPDATE_DEVICE',
  DELETE_DEVICE = 'DELETE_DEVICE',
  ASSIGN_DEVICE = 'ASSIGN_DEVICE',
  UNASSIGN_DEVICE = 'UNASSIGN_DEVICE',

  // Maintenance Management
  CREATE_MAINTENANCE = 'CREATE_MAINTENANCE',
  READ_MAINTENANCE = 'READ_MAINTENANCE',
  UPDATE_MAINTENANCE = 'UPDATE_MAINTENANCE',
  DELETE_MAINTENANCE = 'DELETE_MAINTENANCE',

  // Organization Management
  MANAGE_ORGANIZATION = 'MANAGE_ORGANIZATION',
  READ_ORGANIZATION = 'READ_ORGANIZATION',

  // Role Management
  MANAGE_ROLES = 'MANAGE_ROLES',

  // Employee Management
  MANAGE_EMPLOYEES = 'MANAGE_EMPLOYEES',
  READ_EMPLOYEES = 'READ_EMPLOYEES',

  // Device Request Management
  CREATE_DEVICE_REQUEST = 'CREATE_DEVICE_REQUEST',
  APPROVE_DEVICE_REQUEST = 'APPROVE_DEVICE_REQUEST',
  READ_DEVICE_REQUEST = 'READ_DEVICE_REQUEST',

  // Reports
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_REPORTS = 'EXPORT_REPORTS',

  // Settings
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',

  // Special Permission
  ALL = '*',
  MANAGE_DEVICES = 'MANAGE_DEVICES',
  DEVICE_MANAGEMENT = 'DEVICE_MANAGEMENT',
}
